apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-tp-backend
  namespace: unicorn
spec:
  destination:
    name: unicorn-tp-backend
    namespace: unicorn
  sources:
    - name: unicorn-frontend
      namespace: unicorn
      peer: dc3-default
      action: allow
    - name: unicorn-ssg-frontend
      namespace: unicorn
      # peer: dc3-default
      samenessGroup: ssg-unicorn
      action: allow
