apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-ssg-frontend
  namespace: unicorn
spec:
  destination:
    name: unicorn-ssg-frontend
  sources:
    - name: consul-api-gateway
      namespace: consul
      action: allow