apiVersion: v1
kind: Service
metadata:
  name: prometheus-ingress
  namespace: consul
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090            # Should be the port the Kube LB will listen on to forward to TCP/10000
      targetPort: 9090      # This should line up with the FakeService LISTEN_ADDR: 0.0.0.0:10000