apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: sheol-ext
  namespace: sheol
spec:
  protocol: tcp
  destination:
    addresses:
      - github.com
      - api.github.com
    port: 443