apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: example-tcp
  namespace: default
spec:
  protocol: tcp                 # Only match if the traffic is TLS (SNI match) or an IP. Host headers do NOT match.
  destination:
    addresses:
      - "example.com"
      - "www.wolfmansound.com"
    port: 443