apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: paris
  namespace: paris
spec:
  destination:
    name: paris
    namespace: paris
  sources:
    - name: leroy-jenkins
      namespace: paris
      action: allow
    # - name: unicorn-ssg-frontend
    #   # partition: default
    #   namespace: unicorn
    #   samenessGroup: ssg-unicorn
    #   action: allow