apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: whatismyip
  namespace: externalz
spec:
  destination:
    name: whatismyip
  sources:
    - name: externalz-tcp
      namespace: externalz
      action: allow