apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: example-tcp
  namespace: default
spec:
  destination:
    name: example-tcp
  sources:
    - name: externalz-tcp
      namespace: externalz
      action: allow